# Generated by Django 4.2.7 on 2023-11-20 12:00

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='البلد')),
                ('governorate', models.CharField(blank=True, max_length=100, null=True, verbose_name='المحافظة')),
                ('permission_type', models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10, verbose_name='نوع الصلاحية')),
                ('flash_drive_key', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='مفتاح الفلاش')),
                ('account_expiry_date', models.DateField(blank=True, null=True, verbose_name='تاريخ انتهاء الحساب')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الشركة')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الخدمة')),
                ('description', models.TextField(verbose_name='وصف الخدمة')),
                ('image', models.ImageField(upload_to='services/', verbose_name='صورة الخدمة')),
            ],
        ),
        migrations.CreateModel(
            name='SiteAppearance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_background_image', models.ImageField(blank=True, null=True, upload_to='backgrounds/', verbose_name='صورة خلفية تسجيل الدخول')),
            ],
        ),
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='الصورة')),
                ('caption', models.TextField(blank=True, verbose_name='النص المصاحب')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط؟')),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم (مثال: Facebook)')),
                ('url', models.URLField(verbose_name='الرابط')),
                ('icon_class', models.CharField(max_length=50, verbose_name='فئة الأيقونة (مثال: fab fa-facebook)')),
                ('is_visible', models.BooleanField(default=True, verbose_name='مرئي؟')),
            ],
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموديل')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='core.company', verbose_name='الشركة')),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=100, verbose_name='الصانع')),
                ('year', models.IntegerField(verbose_name='السنة')),
                ('part_number', models.CharField(max_length=100, verbose_name='رقم القطعة')),
                ('crash_in', models.CharField(max_length=100, verbose_name='Crash In')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.company', verbose_name='الشركة')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carmodel', verbose_name='الموديل')),
            ],
        ),
    ]
