# Generated by Django 5.2.7 on 2025-11-03 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='id_chep',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID Chep'),
        ),
        migrations.AddField(
            model_name='car',
            name='read',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Read'),
        ),
        migrations.AddField(
            model_name='car',
            name='write',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Write'),
        ),
    ]
