# -*- coding: utf-8 -*-
"""
Django settings for car_parts_management project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# استيراد الوحدات اللازمة
from pathlib import Path
import os

# بناء المسارات داخل المشروع مثل هذا: BASE_DIR / 'subdir'.
# BASE_DIR يمثل المسار الجذر للمشروع.
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')


# إعدادات الأمان السريعة - غير مناسبة للإنتاج
# انظر https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# مفتاح سري يستخدم للتوقيعات المشفرة. يجب أن يبقى سريًا!
SECRET_KEY = 'django-insecure-your-secret-key-here'

# وضع التصحيح (DEBUG). يجب تعيينه إلى False في بيئة الإنتاج.
DEBUG = True

# قائمة المضيفين المسموح لهم بالوصول إلى التطبيق.
ALLOWED_HOSTS = []


# تعريف التطبيقات
# ------------------------------------------------------------------------------

# قائمة التطبيقات المثبتة في المشروع.
INSTALLED_APPS = [
    'django.contrib.admin',          # لوحة تحكم Django الافتراضية
    'django.contrib.auth',           # نظام المصادقة
    'django.contrib.contenttypes',   # إطار عمل أنواع المحتوى
    'django.contrib.sessions',       # إطار عمل الجلسات
    'django.contrib.messages',       # إطار عمل الرسائل
    'django.contrib.staticfiles',    # لإدارة الملفات الثابتة

    # تطبيقات الطرف الثالث
    'crispy_forms',                  # لتحسين عرض النماذج
    'crispy_bootstrap5',             # حزمة Bootstrap 5 لـ crispy-forms

    # تطبيقات المشروع الخاصة
    'core.apps.CoreConfig',          # تطبيق النماذج الأساسية والمستخدم المخصص
    'main.apps.MainConfig',          # تطبيق الواجهات العامة للموقع
    'dashboard.apps.DashboardConfig',# تطبيق لوحة التحكم المخصصة
]

# البرمجيات الوسيطة (Middleware)
# ------------------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # إدارة الجلسات
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware', # حماية من هجمات CSRF
    'django.contrib.auth.middleware.AuthenticationMiddleware', # ربط المستخدمين بالطلبات
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# إعدادات عناوين URL
# ------------------------------------------------------------------------------

# ملف urls.py الجذري للمشروع
ROOT_URLCONF = 'car_parts_management.urls'

# إعدادات القوالب (Templates)
# ------------------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # تحديد مسار مجلد القوالب على مستوى المشروع
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True, # البحث عن القوالب داخل مجلدات التطبيقات
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# إعدادات WSGI
# ------------------------------------------------------------------------------
WSGI_APPLICATION = 'car_parts_management.wsgi.application'


# إعدادات قاعدة البيانات (SQL Server)
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         # استخدام محرك 'mssql' للاتصال بـ SQL Server
#         'ENGINE': 'mssql',
#         # اسم قاعدة البيانات على الخادم
#         'NAME': 'YourDatabaseName', # <--- استبدل باسم قاعدة بياناتك
#         # اسم المستخدم للوصول إلى قاعدة البيانات
#         'USER': 'YourUsername', # <--- استبدل باسم المستخدم
#         # كلمة المرور للمستخدم
#         'PASSWORD': 'YourPassword', # <--- استبدل بكلمة المرور
#         # عنوان خادم قاعدة البيانات (IP أو اسم المضيف)
#         'HOST': 'YourServerHost', # <--- استبدل بعنوان الخادم
#         # منفذ الاتصال بالخادم
#         'PORT': '1433', # <--- استبدل بالمنفذ الصحيح إذا كان مختلفًا
#         'OPTIONS': {
#             'driver': 'ODBC Driver 17 for SQL Server',
#         },
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'CarSystemDB',
        'HOST': r'ENGBADR\SQLEXPRESS',
        'PORT': '',  # فارغ مع Windows Authentication
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',  # تأكد أن الاسم مطابق لما ظهر في ODBC Drivers
            'trusted_connection': 'yes',  # يستخدم Windows Authentication
        },
    }
}

# إعدادات التحقق من صحة كلمة المرور
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# إعدادات التدويل (Internationalization)
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us' # رمز اللغة الافتراضي

TIME_ZONE = 'UTC' # المنطقة الزمنية الافتراضية

USE_I18N = True # تفعيل نظام الترجمة

USE_TZ = True # تفعيل دعم المناطق الزمنية


# إعدادات الملفات الثابتة (Static files: CSS, JavaScript, Images)
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/howto/static-files/

# STATIC_URL = 'static/' # عنوان URL للملفات الثابتة
# STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')] # مجلد الملفات الثابتة على مستوى المشروع

# إعدادات ملفات الوسائط (Media files: user-uploaded files)
# ------------------------------------------------------------------------------
MEDIA_URL = '/media/' # عنوان URL لملفات الوسائط
MEDIA_ROOT = os.path.join(BASE_DIR, 'media') # المسار الفعلي لمجلد الوسائط


# إعدادات المفتاح الأساسي الافتراضي (Default primary key field type)
# ------------------------------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# إعدادات المصادقة والمستخدم المخصص
# ------------------------------------------------------------------------------

# تحديد نموذج المستخدم المخصص ليكون النموذج الافتراضي للمصادقة
AUTH_USER_MODEL = 'core.User'

# عنوان URL لصفحة تسجيل الدخول. سيتم توجيه المستخدمين غير المسجلين إليه.
LOGIN_URL = 'main:login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
# إعدادات الجلسة (Session)
# ------------------------------------------------------------------------------

# مدة صلاحية ملف تعريف الارتباط للجلسة بالثواني (900 ثانية = 15 دقيقة)
SESSION_COOKIE_AGE = 900

# حفظ الجلسة مع كل طلب لضمان تحديث وقت انتهاء الصلاحية عند الاستخدام
SESSION_SAVE_EVERY_REQUEST = True

# إعدادات Crispy Forms
# ------------------------------------------------------------------------------

# تحديد حزم القوالب المسموح بها
CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"

# تحديد حزمة القوالب الافتراضية لتكون Bootstrap 5
CRISPY_TEMPLATE_PACK = "bootstrap5"
